import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

const pages = ['index.html', 'story.html', 'rules.html', 'product.html'];
const source = Object.fromEntries(pages.map((page) => [page, readFileSync(page, 'utf8')]));
const styles = readFileSync('styles.css', 'utf8');
const mobileStyles = styles.slice(styles.indexOf('@media (max-width: 820px)'), styles.indexOf('@media (max-width: 430px)'));
const animations = readFileSync('animations.js', 'utf8');
const game = readFileSync('game.mjs', 'utf8');
const favicon = readFileSync('favicon.js', 'utf8');

for (const page of pages) {
  assert.match(source[page], /<link rel="stylesheet" href="styles\.css\?v=\d+" \/>/, `${page} loads the cache-busted responsive styles`);
  assert.match(source[page], /<script type="module" src="animations\.js\?v=\d+"><\/script>/, `${page} loads the cache-busted local animations`);
  assert.match(source[page], /<link rel="shortcut icon" type="image\/x-icon" href="favicon\.ico\?v=2" sizes="any" \/>/, `${page} has a root ICO fallback`);
  assert.match(source[page], /<link rel="icon" type="image\/png" href="assets\/favicon-open\.png\?v=2" sizes="128x128" data-animated-favicon \/>/, `${page} has a cache-busted animated favicon`);
  assert.match(source[page], /<script src="favicon\.js" defer><\/script>/, `${page} loads the alternating favicon`);
  assert.match(source[page], /assets\/prototype\/brand-wordmark\.png/, `${page} uses the supplied wordmark`);
  assert.match(source[page], /assets\/prototype\/brand-mark-red\.png/, `${page} uses the supplied footer mark`);
  assert.match(source[page], /class="footer-wordmark"/, `${page} footer uses the supplied wordmark`);
  assert.match(source[page], /Lấy cảm hứng từ truyền thuyết Nàng Han/, `${page} footer follows the supplied brand copy layout`);
  assert.match(source[page], /class="nav-cta"[^>]*>Trải nghiệm ngay!<\/a>/, `${page} has the outlined experience CTA`);
}

assert.match(source['story.html'], /class="story-hero"/, 'story opens with the supplied framed hero composition');
assert.match(source['story.html'], /class="story-hero-art" aria-hidden="true"><\/div>/, 'story hero keeps the wireframe media frame empty');
assert.doesNotMatch(source['story.html'], /story-hero-copy/, 'story hero does not fill the wireframe media placeholder');
assert.match(source['story.html'], /Bạn chiến đấu[\s\S]*vì điều gì\?/, 'story hero keeps the wireframe question');
assert.match(source['story.html'], /class="[^"]*story-legend-layout[^"]*"/, 'story uses the supplied editorial legend layout');
assert.match(source['story.html'], /Truyền thuyết Nàng Han/, 'story uses the supplied legend title');
assert.match(source['story.html'], /Quẵm tỗ Nãng Han/, 'story keeps the supplied Thai title');
assert.match(source['story.html'], /NNƯT\. Cầm Văn Vui/, 'story credits the supplied source document');
assert.match(source['story.html'], /Người Thái Tây Bắc có câu chuyện truyền thuyết Nàng Han/, 'story contains the supplied full original text');
assert.match(source['story.html'], /class="story-sheet" tabindex="0"/, 'the long story is keyboard-scrollable inside its frame');
assert.match(source['story.html'], /family=Roboto:wght@400;500;700/, 'story loads Roboto for long-form reading');
assert.match(styles, /--font-reading: "Roboto"/, 'story defines a dedicated Roboto reading token');
assert.match(styles, /assets\/prototype\/story-frame-floral\.png/, 'story uses the supplied floral frame asset');
assert.match(styles, /\.story-sheet-frame::before \{[^}]*width: 100vw;[^}]*height: 17\.2%;[^}]*background: #10102d;/, 'story extends the navy base across the full viewport');
assert.match(styles, /\.story-sheet \{[^}]*top: 16\.5%;[^}]*height: 46\.5%;/, 'story text stays inside the floral frame while scrolling');
assert.match(styles, /\.story-legend-layout \{[^}]*minmax\(0, 800px\)[^}]*width: min\(1480px, calc\(100% - 2rem\)\)/, 'story gives the floral reading frame more room on desktop');
assert.match(styles, /\.story-sheet p \{[^}]*font-size: clamp\(\.92rem, 1\.05vw, 1\.05rem\)/, 'story body copy grows with the larger reading frame');
assert.doesNotMatch(source['story.html'], /story-legacy|Từ truyền thuyết đến một cuộc chơi chung/, 'story flows directly from the legend to the product scene');
assert.match(source['story.html'], /assets\/prototype\/story-board-clean\.png/, 'story closes with the clean board background');
assert.match(source['story.html'], /assets\/prototype\/story-piece-male-correct\.png/, 'story layers the correct male piece over the board');
assert.match(source['story.html'], /assets\/prototype\/story-piece-female-correct\.png/, 'story layers the correct female piece over the board');
assert.match(source['story.html'], /assets\/prototype\/story-die-small\.png/, 'story layers the small square-pip die');
assert.match(source['story.html'], /assets\/prototype\/story-die-large\.png/, 'story layers the large round-pip die');
assert.doesNotMatch(source['story.html'], /assets\/prototype\/product-board-scene\.png/, 'story keeps the four moving objects separate from the board');
assert.match(styles, /\.story-product-cta a \{[^}]*top: 50%;[^}]*left: 50%;[^}]*translate: -50% -50%;/, 'story product CTA stays centered on the board scene');
assert.match(styles, /\.story-product-cta a \{[^}]*min-height: 72px;[^}]*padding: 1\.1rem 2rem;[^}]*font-size: 1\.5rem;/, 'story product CTA stays prominent over the board scene');
assert.match(styles, /\.story-scene-piece-male \{ left: 11\.5%; bottom: 49%; height: 43%; \}/, 'male piece stands on the raised left platform');
assert.match(styles, /\.story-scene-piece-female \{ right: 17%; bottom: 38%; height: 50%; \}/, 'female piece stands on the right flower cell');
assert.match(styles, /\.story-product-cta::before \{[^}]*assets\/prototype\/border-horizontal\.png[^}]*repeat-x;/, 'story keeps the wireframe triangle divider above the board scene');
assert.match(styles, /\.story-product-cta img \{ min-height: 0; \}/, 'story board scene keeps its natural mobile aspect ratio');
assert.match(animations, /function initStorySceneMotion\(\)/, 'anime.js initializes the layered story scene motion');
assert.match(animations, /\.story-scene-piece-male/, 'story motion targets the correct male piece');
assert.match(animations, /\.story-scene-die/, 'story motion targets both differently sized dice');

assert.match(source['rules.html'], /class="rules-overview"/, 'rules start with a board overview from the wireframe');
assert.match(source['rules.html'], /assets\/prototype\/team-allies\.png/, 'rules show the supplied Nàng Han faction panel');
assert.match(source['rules.html'], /assets\/prototype\/team-opponents\.png/, 'rules show the supplied opposing faction panel');
assert.match(source['rules.html'], /class="setup-steps"/, 'rules explain the three setup steps before play');
assert.equal((source['rules.html'].match(/class="rule-divider"/g) ?? []).length, 2, 'rules guide keeps both wireframe dividers');
assert.match(source['rules.html'], /class="rules-copy-heading"/, 'rules heading keeps the wireframe action sequence');
assert.match(source['rules.html'], /Lắc xúc xắc → Xuất quân\/Di chuyển → Bốc thẻ bài/, 'rules show the turn order from the wireframe');
assert.match(source['rules.html'], /class="win-condition"/, 'rules keep the wireframe victory row');
assert.doesNotMatch(source['rules.html'], /class="rule-columns"/, 'rules are prose instead of an unrelated card grid');
assert.match(source['rules.html'], /class="rules-demo"/, 'rules keep the live demo in the wireframe flow');
assert.doesNotMatch(source['rules.html'], /team-strip|data-player-card/, 'live demo does not repeat the faction overview');
assert.equal((source['rules.html'].match(/data-game-board/g) ?? []).length, 1, 'rules keep exactly one playable board');
assert.equal((source['rules.html'].match(/class="map-note /g) ?? []).length, 13, 'board overview keeps all thirteen wireframe callouts');
assert.equal((source['rules.html'].match(/<button[^>]+class="map-marker /g) ?? []).length, 20, 'all annotated and grouped board cells are interactive buttons');
assert.equal((source['rules.html'].match(/data-map-hotspot/g) ?? []).length, 20, 'all annotated and grouped board cells are interactive hotspots');
assert.equal((source['rules.html'].match(/data-map-group="start"/g) ?? []).length, 4, 'all four start cells share one highlight group');
assert.equal((source['rules.html'].match(/data-map-group-cell="special"/g) ?? []).length, 7, 'the seven additional flower cells join the special-cell highlight group');
assert.equal((source['rules.html'].match(/data-map-group="special"/g) ?? []).length, 1, 'the annotated flower cell controls the special-cell group');
assert.equal((source['rules.html'].match(/class="map-note [^>]+ hidden/g) ?? []).length, 13, 'board callouts stay hidden until a hotspot is selected');
assert.equal((source['rules.html'].match(/aria-expanded="false"/g) ?? []).length >= 20, true, 'board hotspots expose their collapsed state');
assert.match(animations, /function initMapExplorer\(\)/, 'anime.js initializes the interactive board explorer');
assert.match(animations, /const clearMapSelection = \(\) =>/, 'the board explorer has one shared reset path');
assert.match(animations, /const highlightGroup = \(hotspot\) =>/, 'the board explorer can reveal every cell in a matching group');
assert.match(animations, /const group = hotspot\?\.dataset\.mapGroup \|\| hotspot\?\.dataset\.mapGroupCell;/, 'each grouped flower hotspot can reveal its complete group');
assert.match(animations, /document\.addEventListener\('click'/, 'clicking outside the selected board cell resets the explorer');
assert.match(animations, /closest\('\[data-map-hotspot\]'\)/, 'clicking another hotspot does not trigger the outside reset');
assert.match(animations, /resizeHotspot\(hotspot, 1\.26\)/, 'hovering an annotated board cell visibly zooms it');
assert.match(animations, /hotspot\.matches\('\[class\*="-goal"\]'\) \? 1 : scale/, 'finish lanes stay aligned to their printed frames');
assert.match(animations, /const preview = \(hotspot\) => \{[\s\S]*showNote\(hotspot\)/, 'hovering a board hotspot immediately shows its callout');
assert.equal((source['rules.html'].match(/data-map-hotspot data-map-group-cell="special"/g) ?? []).length, 7, 'every additional flower cell is an interactive hotspot');
assert.doesNotMatch(styles, /\.map-group-cell \{ pointer-events: none; \}/, 'flower-cell hotspots accept pointer interaction');
assert.equal((source['rules.html'].match(/data-map-group="normal" data-map-cell=/g) ?? []).length, 4, 'the four annotated normal cells seed the normal-cell group');
assert.equal((animations.match(/'\d+-\d+:map-note-(?:north|west|east|south)-normal'/g) ?? []).length, 36, 'the remaining normal cells are generated as interactive hotspots');
assert.match(animations, /normalCells\.forEach\(\(cell\) =>/, 'every normal board cell receives the shared interaction behavior');
assert.match(styles, /\.rules-map figcaption \{ position: absolute;/, 'desktop board callouts are positioned around the board');
assert.match(styles, /\.marker-han-goal, \.marker-ally-goal \{ width: 13\.333%; height: 42\.667%;/, 'vertical finish markers cover their complete lanes');
assert.match(styles, /\.marker-enemy-goal, \.marker-rival-goal \{ width: 42\.667%; height: 13\.333%;/, 'horizontal finish markers cover their complete lanes');
assert.match(styles, /\.marker-han-goal \{[^}]*polygon\(25% 0, 75% 0, 100% 100%, 0 100%\)/, 'north finish highlight excludes neighboring cells at its narrow end');
assert.match(styles, /\.map-marker::before \{[^}]*mix-blend-mode: multiply;/, 'highlighted board areas keep the board artwork fully saturated');
assert.match(styles, /\.map-marker\.is-group-highlight::before \{ opacity: 1; \}/, 'grouped board cells become fully visible together');
assert.match(styles, /var\(--cell-x, 50%\) var\(--cell-y, 50%\)/, 'lane highlights retain the board image without per-cell coordinates');
assert.match(styles, /\.marker-han-start \{ top: 0; left: 33\.333%; --cell-x: 35\.714%; --cell-y: 0%; \}/, 'board markers use the board asset grid');
assert.match(styles, /\.marker-east-start \{ top: 33\.333%; right: 0; --cell-x: 100%; --cell-y: 35\.714%; \}/, 'east start marker matches its board square');
assert.match(styles, /\.marker-special-east-north \{ top: 33\.333%; left: 80%; --cell-x: 85\.714%; --cell-y: 35\.714%; \}/, 'upper-right flower marker matches its board square');
assert.match(styles, /\.marker-special-east-south \{ top: 60%; left: 73\.333%; --cell-x: 78\.571%; --cell-y: 64\.286%; \}/, 'lower-right flower marker matches its board square');
assert.match(styles, /\.marker-special-south-west \{ top: 93\.333%; left: 33\.333%; --cell-x: 35\.714%; --cell-y: 100%; \}/, 'bottom-left flower marker matches the final board row');
assert.match(styles, /\.marker-ally-start \{ right: 33\.333%; bottom: 0; --cell-x: 64\.286%; --cell-y: 100%; \}/, 'ally start marker matches its board square');
assert.match(styles, /\.marker-west-normal \{ top: 33\.333%; left: 0; --cell-x: 0%; --cell-y: 35\.714%; \}/, 'west normal marker matches the wireframe row');
assert.match(styles, /\.marker-south-normal \{ top: 86\.667%; left: 33\.333%; --cell-x: 35\.714%; --cell-y: 92\.857%; \}/, 'south normal marker matches the wireframe branch');
assert.match(source['rules.html'], /Hàng về đích<br \/>đội Quân địch/, 'rival finish lane keeps its wireframe callout');
assert.match(styles, /\.note-enemy-goal::after \{[^}]*border-left: 2px solid currentColor;/, 'enemy finish label points vertically to its lane');
assert.match(styles, /\.note-rival-goal::after \{[^}]*border-left: 2px solid currentColor;/, 'rival finish label points vertically to its lane');
assert.match(styles, /\.map-note \{ position: static;/, 'mobile board callouts return to document flow');

assert.match(favicon, /\[data-animated-favicon\]/, 'favicon animation targets only the animated PNG link');
assert.match(favicon, /favicon-open\.png\?v=2/, 'favicon animation includes a cache-busted open-eye frame');
assert.match(favicon, /favicon-closed\.png\?v=2/, 'favicon animation includes a cache-busted closed-eye frame');
assert.match(favicon, /prefers-reduced-motion/, 'favicon animation respects reduced-motion preferences');

assert.match(source['index.html'], /class="character-path"/, 'home connects the character and navigation path');
assert.equal((source['index.html'].match(/class="directory-link"/g) ?? []).length, 3, 'home has three destination links');
assert.equal((source['index.html'].match(/class="banner-button"/g) ?? []).length, 2, 'home banner has two destination actions');
assert.match(source['index.html'], /Khám phá câu chuyện/, 'home banner links to the story');
assert.match(source['index.html'], /Trải nghiệm sản phẩm/, 'home banner links to the product');
assert.match(source['index.html'], /href="story\.html"/);
assert.match(source['index.html'], /href="rules\.html"/);
assert.match(source['index.html'], /href="product\.html"/);
assert.doesNotMatch(source['index.html'], /↗/, 'home branches contain text without arrow icons');
assert.match(source['index.html'], /assets\/prototype\/character-white\.png/, 'home uses the supplied white character');
assert.match(source['index.html'], /assets\/prototype\/character-navy\.png/, 'home uses the supplied navy character');
assert.match(source['index.html'], /assets\/prototype\/brand-mark-yellow\.png/, 'home uses the supplied product mark');
assert.match(source['index.html'], /Bạn đã sẵn sàng bước vào hành trình/, 'home video follows the supplied wireframe heading');
assert.match(styles, /assets\/prototype\/directory-frame\.png/, 'home uses the supplied directory frame');
assert.match(styles, /assets\/prototype\/branch-button\.png/, 'home uses the supplied button motif on each branch');
assert.match(styles, /assets\/prototype\/video-frame\.png/, 'home uses the supplied video frame');
assert.match(styles, /assets\/prototype\/product-frame\.png/, 'home uses the supplied product frame');
assert.match(styles, /\.home-product::before, \.home-product::after/, 'home product keeps independent responsive side decorations');
assert.match(styles, /\.home-product::before[^}]*background-position:\s*left center/, 'home product anchors the left frame without stretching');
assert.match(styles, /\.home-product::after[^}]*background-position:\s*right center/, 'home product anchors the right frame without stretching');
assert.match(styles, /\.product-teaser \{[^}]*width:\s*min\(1440px, max\(960px, 75vw\), calc\(100% - 4rem\)\)[^}]*gap:\s*clamp\(1\.25rem, 3\.125vw, 3\.75rem\)/, 'home product scales with wide desktop viewports');
assert.match(styles, /\.product-image-slot \{[^}]*width:\s*min\(100%, clamp\(250px, 17\.5vw, 400px\)\)/, 'home product side frames grow on wide screens');
assert.match(styles, /\.product-kicker \{[^}]*font-size:\s*clamp\(1\.3rem, 1\.8vw, 2\.25rem\)/, 'home product ownership label stays prominent');
assert.match(styles, /\.product-feature-mark \{[^}]*height:\s*clamp\(260px, 17\.5vw, 400px\)/, 'home product mark leaves more room for the surrounding copy');
assert.match(source['index.html'], /data-client-image-slot="right"><\/div>\s*<div class="product-action">/, 'home product copy follows all three showcase columns');
assert.match(styles, /\.product-action \{[^}]*grid-column:\s*1 \/ -1;[^}]*gap:\s*clamp\(1\.5rem, 1\.75vw, 2rem\)/, 'home product copy and CTA keep clear separation');
assert.match(styles, /\.product-action h2 \{[^}]*font-size:\s*clamp\(1\.5rem, 2\.5vw, 2\.75rem\)/, 'home product tagline stays prominent beneath the showcase');
assert.match(styles, /\.product-action \.button \{[^}]*min-height:\s*80px;[^}]*font-size:\s*clamp\(1\.25rem, 1\.35vw, 1\.5rem\)/, 'home product CTA keeps the enlarged readable treatment');
assert.match(styles, /\.button \{[^}]*min-height: 56px;[^}]*padding: \.9rem 1\.5rem;/, 'shared text buttons use a larger touch target');
assert.match(styles, /\.banner-button \{[^}]*min-height: 64px;[^}]*padding: 1rem 1\.5rem;[^}]*font-size: 1\.05rem;/, 'home banner buttons use the larger CTA scale');
assert.match(styles, /\.demo-actions button \{[^}]*min-height: 54px;[^}]*padding: \.8rem 1rem;[^}]*font-size: 1\.05rem;/, 'rules demo buttons use the larger control scale');
assert.match(styles, /\.home-directory::before/, 'home directory draws a central spine');
assert.match(styles, /\.home-directory\s*\{[^}]*width:\s*min\(100vw, 1440px\)/, 'home directory keeps the complete frame within a fixed maximum width');
assert.match(styles, /\.home-directory\s*\{[^}]*margin-left:\s*50%[^}]*transform:\s*translateX\(-50%\)/, 'home directory keeps the fixed frame centered');
assert.match(styles, /\.home-directory\s*\{[^}]*aspect-ratio:\s*2917\s*\/\s*1409/, 'home directory preserves the supplied frame aspect ratio');
assert.match(styles, /\.home-directory\s*\{[^}]*background-size:\s*contain/, 'home directory scales the decorative frame without distortion');
assert.match(styles, /\.directory-link:nth-child\(odd\)/, 'odd branches sit on one side');
assert.match(styles, /\.directory-link:nth-child\(even\)/, 'even branches sit on the other side');
assert.match(mobileStyles, /\.story-legend-layout \{ grid-template-columns: repeat\(2, minmax\(0, 1fr\)\); width: 100%;/, 'story labels share the row above the full-width mobile frame');
assert.match(mobileStyles, /\.story-sheet-frame \{ grid-column: 1 \/ -1; grid-row: 2;/, 'story frame ends the legend section before the product scene');
assert.match(mobileStyles, /\.faction-panels, \.setup-steps \{ grid-template-columns: 1fr; \}/, 'rules factions and setup steps stack on mobile');
assert.match(animations, /\[data-animated-button\]/, 'anime.js animates the shared CTA buttons');
assert.match(animations, /from '\.\/assets\/vendor\/anime\.esm\.min\.js'/, 'anime.js is served locally so CTA animation is not blocked by the browser');
assert.doesNotMatch(animations, /new IntersectionObserver/, 'scrolling does not transform whole page sections');
assert.doesNotMatch(animations, /main > section:not\(:first-child\), \.site-footer/, 'footer stays inside the mobile scroll range');

assert.match(source['rules.html'], /cờ cá ngựa/i, 'rules explain the familiar horse-racing foundation');
assert.match(source['rules.html'], /ô đặc biệt/i, 'rules explain special board spaces');
assert.match(source['rules.html'], /rút một thẻ/i, 'rules connect special spaces to the card deck');
assert.equal((source['rules.html'].match(/class="game-card"/g) ?? []).length, 10, 'rules show ten sample action cards');
assert.equal((source['rules.html'].match(/data-card-toggle/g) ?? []).length, 10, 'each action card can be opened');
assert.equal((source['rules.html'].match(/aria-controls="card-reader"/g) ?? []).length, 10, 'each action card opens the shared detail reader');
assert.equal((source['rules.html'].match(/data-card-description=/g) ?? []).length, 10, 'each action card includes its complete guide description');
assert.match(source['rules.html'], /<dialog[^>]*data-card-reader/, 'card details open in a native dialog');
assert.match(source['rules.html'], /data-card-reader-close/, 'the card dialog has an accessible close control');
assert.match(animations, /cardReader\.showModal\(\)/, 'selecting a card opens its detail dialog');
assert.match(animations, /cardReader\.close\(\)/, 'the card dialog can be closed without leaving the page');
assert.match(styles, /\.game-card\s*\{[^}]*aspect-ratio:\s*709\s*\/\s*1063/, 'action cards share the source card ratio');
assert.match(styles, /\.card-reader\[open\]\s*\{[^}]*display:\s*grid;[^}]*grid-template-columns:\s*minmax\(180px, 280px\) 1fr/, 'the open card dialog uses a readable guide layout');
assert.match(styles, /\.game-console\s*\{[^}]*transform:\s*none\s*!important/, 'mobile action bar is not trapped by animation transforms');
assert.match(styles, /\.rules-map-board\.is-exploring > img \{[^}]*opacity:\s*\.28;/, 'exploring a board cell dims the remaining board');
assert.match(styles, /\.horse-piece \{[^}]*width: clamp\(50px, 7vw, 92px\);[^}]*height: clamp\(50px, 7vw, 92px\);[^}]*rgba\(255,255,255,1\)[^}]*translate: -50% -92%;/, 'demo pieces stay large, glow white and sit slightly below the board-cell center');
assert.match(styles, /\.horse-piece img \{[^}]*brightness\(1\.1\)[^}]*saturate\(1\.6\)[^}]*contrast\(1\.18\)/, 'demo piece artwork stays deep and vivid');
assert.match(styles, /\.art-board > img \{[^}]*opacity:\s*\.78;/, 'demo board is softened so pieces remain visible');
assert.match(source['rules.html'], /data-game-board/, 'rules include the playable horse-racing board');
assert.equal((source['rules.html'].match(/data-demo-action=/g) ?? []).length, 6, 'rules expose six guided demo actions');
assert.match(source['rules.html'], /data-demo-action="release"/, 'rules include the release action');
assert.match(source['rules.html'], /data-demo-action="special"/, 'rules include the special-cell action');
assert.match(source['rules.html'], /data-demo-action="capture"/, 'rules include the capture action');
assert.match(source['rules.html'], /Bàn chơi thử/, 'rules use client-friendly demo language');
assert.match(source['rules.html'], /chạm vào bàn cờ để mở các nút thao tác/, 'mobile guidance explains board controls');
assert.match(game, /toggleMobileActions/, 'mobile board can toggle its action controls');
assert.match(game, /mobile-board-trigger/, 'mobile board has an action trigger');
assert.match(source['rules.html'], /<script type="module" src="game\.mjs\?v=7"><\/script>/, 'rules load the cache-busted game engine');

console.log('Page structure checks passed.');
